[package]
name = "hatchlingwm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.0"
bitflags = "2.6.0"
env_logger = "0.11.0"
log = "0.4.10"
smithay = { git = "https://github.com/Smithay/smithay" }
